export const ROUTES = {
  about: '/about',
  home: '/',
  login: '/login',
  properties: '/properties',
  lease : '/lease-property/:id',
  tenancyRequestDetail: '/tenancy-request/:id',
  contact: '/contact',
  property: '/properties/:id',
  register: '/register',
  confirmEmail: '/email/confirm/:token',
  profile: '/profile',
  addNewListing: '/add-new-listing',
  realtorsProperties: '/realtor-properties',
  change_password: '/change-password',
  forgot_password: '/forgot-password',
  reset_password: '/reset-password/:token',
  settings: '/settings',
};
